// ============================================================================
//
// Copyright (C) 2006-2012 Talend Inc. - www.talend.com
//
// This source code is available under agreement available at
// %InstallDIR%\features\org.talend.rcp.branding.%PRODUCTNAME%\%PRODUCTNAME%license.txt
//
// You should have received a copy of the agreement
// along with this program; if not, write to Talend SA
// 9 rue Pages 92150 Suresnes, France
//
// ============================================================================
package org.talend.core.model.genhtml;

import org.talend.commons.xml.XmlUtil;

/**
 * This class is stored all constants for generating HTML. <br/>
 * 
 */
public interface IHTMLDocConstants {

    public static final String PIC_FOLDER_NAME = "pictures"; //$NON-NLS-1$

    public static final String TEMP_FOLDER_NAME = "userHTMLDoc"; //$NON-NLS-1$

    public static final String EMPTY_ELEMENT_VALUE = "none"; //$NON-NLS-1$

    public static final String TITLE = "Generated by Talend Open Studio. (www.talend.com)"; //$NON-NLS-1$

    public static final String TITLE_GEN = "Generated by "; //$NON-NLS-1$

    public static final String VERSION = " VERSION "; //$NON-NLS-1$

    public static final String JOB_PREVIEW_PIC_SUFFIX = ".png"; //$NON-NLS-1$

    public static final String PICTUREFOLDERPATH = "pictures/"; //$NON-NLS-1$

    public static final String EXTERNAL_NODE_PREVIEW = "external_preview_"; //$NON-NLS-1$

    public static final String TALEND_LOGO_FILE_NAME = "logo.jpg"; //$NON-NLS-1$

    public static final String MAIN_XSL_FILE_PATH = "resources/Job.xsl"; //$NON-NLS-1$

    public static final String MAIN_XSL_ANALYSIS_PATH = "resources/Analysis.xsl"; //$NON-NLS-1$

    public static final String MAIN_XSL_JOBCOMPARE_PATH = "resources/JobCompare.xsl"; //$NON-NLS-1$

    public static final String LOGO_FILE_PATH = "icons/logo.jpg"; //$NON-NLS-1$

    public static final String WEBSITE_LINK = "http://www.talend.com"; //$NON-NLS-1$

    public static final String REPOSITORY = "REPOSITORY"; //$NON-NLS-1$

    public static final String REPOSITORY_BUILT_IN = "BUILT_IN"; //$NON-NLS-1$

    public static final String DISPLAY_BUILT_IN = "Built-In"; //$NON-NLS-1$

    public static final String REPOSITORY_COMMENT = "COMMENT"; //$NON-NLS-1$

    public static final String DISPLAY_COMMENT = "Comment"; //$NON-NLS-1$

    public static final String UNKNOWN = "UNKNOWN"; //$NON-NLS-1$

    public static final String XML_FILE_SUFFIX = XmlUtil.FILE_XML_SUFFIX;

    public static final String HTML_FILE_SUFFIX = ".html"; //$NON-NLS-1$

    public static final String TMAP_XSL_FILE_PATH = "resources/tMap.xsl"; //$NON-NLS-1$

    public static final String MAPPERCOMPONENT_XSL_FILE_PATH = "resources/mapperComponent.xsl"; //$NON-NLS-1$

    public static final String TROWGENERATOR_XSL_FILE_PATH = "resources/tRowGenerator.xsl"; //$NON-NLS-1$

    public static final String MAPPER_TABLE_INPUT = "input"; //$NON-NLS-1$

    public static final String MAPPER_TABLE_OUPUT = "output"; //$NON-NLS-1$

    public static final String MAPPER_TABLE_VAR = "var"; //$NON-NLS-1$

    public static final String EXTERNAL_FOLDER_NAME = "externalDoc/"; //$NON-NLS-1$

    public static final String JOB_NODE_DOCUMENTATION_ROOT_PATH = "documentations/generated/jobs"; //$NON-NLS-1$

    public static final String JOBLET_NODE_DOCUMENTATION_ROOT_PATH = "documentations/generated/joblets"; //$NON-NLS-1$

    public static final String GENERATED_NODE_DOCUMENTATION_ROOT_PATH = "documentations/generated"; //$NON-NLS-1$

    public static final String REPOSITORY_PLUG_IN_ID = "org.talend.repository"; //$NON-NLS-1$

    public static final String JOB_DOC_LIST_HTML_NAME = "jobsdoclist.html"; //$NON-NLS-1$

    public static final String JOBLET_DOC_LIST_HTML_NAME = "jobletsdoclist.html"; //$NON-NLS-1$

    public static final String PROJECT_DOC_LIST_HTML_NAME = "projectsdoclist.html"; //$NON-NLS-1$

    public static final String JOB_DOC_LIST_XML_NAME = "jobsdoclist.xml"; //$NON-NLS-1$

    public static final String JOBLET_DOC_LIST_XML_NAME = "jobletsdoclist.xml"; //$NON-NLS-1$

    public static final String PROJECT_DOC_LIST_XML_NAME = "projectsdoclist.xml"; //$NON-NLS-1$

    public static final String TIDY_PROPERTIES_FILE = "resources/tidy.properties"; //$NON-NLS-1$

    public static final String GENERATE_ALL_DOC_LIST_XSL = "resources/generate_doc_list.xsl"; //$NON-NLS-1$
}
